apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.AdminPassword }}
  release-password:  {{ .Values.AdminPassword | b64enc | quote }}
  {{ else }}
  release-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.xlrLicense }}
  xlr-License: {{ .Values.xlrLicense | b64enc | quote }}
  {{ end }}
  {{ if .Values.RepositoryKeystore }}
  repositoryKeystore: {{ .Values.RepositoryKeystore | b64enc | quote }}
  {{ end }}
  {{ if .Values.KeystorePassphrase }}
  keystorePassphrase: {{ .Values.KeystorePassphrase | b64enc | quote }}
  {{ end }}
  {{ if .Values.UseExistingDB.Enabled }}
  databaseUsername: {{ .Values.UseExistingDB.XLR_DB_USER | b64enc | quote }}
  databasePassword: {{ .Values.UseExistingDB.XLR_DB_PASS | b64enc | quote }}
  reportDatabaseUsername: {{ .Values.UseExistingDB.XLR_REPORT_DB_USER | b64enc | quote }}
  reportDatabasePassword: {{ .Values.UseExistingDB.XLR_REPORT_DB_PASS | b64enc | quote }}
  {{ end }}
  {{ if .Values.UseExistingMQ.Enabled }}
  rabbitmqUsername: {{ .Values.UseExistingMQ.XLR_TASK_QUEUE_USERNAME | b64enc | quote }}
  rabbitmqPassword: {{ .Values.UseExistingMQ.XLR_TASK_QUEUE_PASSWORD | b64enc | quote }}
  {{ end }}
